create table COCKTAIL_SHOPPING_LIST(
  SHOPPINGLISTID UUID,
  COCKTAILID UUID,
  PRIMARY KEY(SHOPPINGLISTID,COCKTAILID),
  FOREIGN KEY(SHOPPINGLISTID)
  REFERENCES SHOPPING_LIST (SHOPPINGLISTID),
  FOREIGN KEY(COCKTAILID)
  REFERENCES COCKTAIL (COCKTAILID)

);